#!/bin/bash -e

echo "Installing Precommit hook..."
cd .git/hooks
PRECOMMITFILE=pre-commit
touch $PRECOMMITFILE
> $PRECOMMITFILE
echo "> ./README.md && cat ./src/docs/*.md >> ./README.md && git add ./README.md" >> $PRECOMMITFILE
chmod +x $PRECOMMITFILE